In [964]:
1 #Numpy -> its a multidimensional array librabry .i,e u can store all sort of data.like 1-d,2-d,n-d;
#downloading Numpy(remeber to pip or pip3 install numpy first on terminal)

1

In [965]:
import numpy as np

#THE BASICS :

#initialize array

1 a=np.array([1,2,3],dtype="int16")

In [966]:
#initialize array
a=np.array([1,2,3],dtype="int16") # with assigning to dtype i,e keyword argument we  can make it possible to store our data in specified number of bytes
#but it need to fit into that specified byte of storage; 
print("one dimensional array :",a)

one dimensional array : [1 2 3]


In [967]:
b=np.array([[1.0,2.0,3.0,5.8],[2.1,3,4.2,4.5]])
print("two dimensional array :",b)

two dimensional array : [[1.  2.  3.  5.8]
 [2.1 3.  4.2 4.5]]


In [968]:
#Get Dimension
print("dimension of a :",a.ndim)
print("dimension of b :",b.ndim)


dimension of a : 1
dimension of b : 2


In [969]:
a.ndim
b.ndim

2

In [970]:
#Get Shape
print("shape of a :",a.shape) #its a vector so its tellings us one dimension 
print("shape of b :",b.shape)


shape of a : (3,)
shape of b : (2, 4)


In [971]:
#Get  Type
print("a type is :",a.dtype)

#Get Size
print("size of a :",a.size) # # of element in the array.i,e length of array;


a type is : int16
size of a : 3


In [972]:
#total size
print("a item size :",a.itemsize) # size of single element in the array .i,e in bytes;
print("total size is a:",a.size*a.itemsize)

a item size : 2
total size is a: 6


In [973]:
b

array([[1. , 2. , 3. , 5.8],
       [2.1, 3. , 4.2, 4.5]])

In [974]:
#ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS ETC

#Get specific element [row,column] -ve index is possible similar to list;
b[1,2]


np.float64(4.2)

In [975]:
#Get specific row [row,:]#we use slicing(:) operation
print("row :",b[1,0:2]);

row : [2.1 3. ]


In [976]:

#Get specific column[:,column]
print("column :",b[:,1])

column : [2. 3.]


In [977]:
#Getting a little more fancy [starindex:endindex:steps]
print("subset of specific row",b[1,1::2])


subset of specific row [3.  4.5]


In [978]:
#change element
b[1,2]=8
print(b)


[[1.  2.  3.  5.8]
 [2.1 3.  8.  4.5]]


In [979]:
b.dtype

dtype('float64')

In [980]:
b[:,2]=[9,4]
b

array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])

In [981]:
int(1.2)

1

# 3-d Example

In [982]:
c=np.array([[
         [1,2],[3,4]
             ],
             [
                 [5,6],[7,8]
             ]
])


In [983]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [984]:
type(c)

numpy.ndarray

In [985]:
c.ndim

3

In [986]:
c.shape

(2, 2, 2)

## calculate the memory space took for c numpy array

In [987]:
c.dtype

dtype('int64')

In [988]:
c.itemsize *c.size

64

In [989]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [990]:
#get specific element (work outside in)
print("specified element is :",c[0,1])

specified element is : [3 4]


In [991]:
c[1,1] = 100
c

array([[[  1,   2],
        [  3,   4]],

       [[  5,   6],
        [100, 100]]])

In [992]:
b.shape

(2, 4)

# Initializing Different types of arrays

In [993]:
zm = np.zeros((3,4))

In [994]:
zm.ndim

2

In [995]:
zm.shape

(3, 4)

All 1's matrix

In [996]:
np.ones((3,3)) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [997]:
np.ones((3,3),dtype="int16")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [998]:
ones = np.ones((3,3),dtype="int16")

In [999]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [1000]:
ones[1,1] = 100
ones

array([[  1,   1,   1],
       [  1, 100,   1],
       [  1,   1,   1]], dtype=int16)

In [1001]:
#any other number
np.full(ones.shape,88)

array([[88, 88, 88],
       [88, 88, 88],
       [88, 88, 88]])

In [1002]:
#any other number
m100=np.full((4,5),100,dtype="float")

# reues the already existing array and assign one value to element

In [1003]:
np.full_like(m100,200,dtype="float")


array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

In [1004]:
np.random.random_sample((2,3))

array([[0.22768097, 0.66722877, 0.5575137 ],
       [0.89393017, 0.1516531 , 0.51207348]])

In [1005]:
np.random.rand(4,3)

array([[0.55715855, 0.06475702, 0.95302464],
       [0.18722358, 0.2538805 , 0.95840622],
       [0.50164898, 0.34744344, 0.66990485],
       [0.56907384, 0.51092465, 0.4220605 ]])

In [1006]:
np.random.randint(2,9,size=(3,3))

array([[5, 5, 3],
       [2, 7, 3],
       [4, 2, 6]], dtype=int32)

#Generate identity matrix only one argument because identity matrix is a square matrix
np.identity(5)

In [1007]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [1008]:
np.identity(5)# 5,5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])